functionsDirectory = "/Users/test/startups/deploy-68cc53904a126d00086a9168/netlify/functions"
functionsDirectoryOrigin = "ui"
headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[build]
publish = "/Users/test/startups/deploy-68cc53904a126d00086a9168"
publishOrigin = "config"
commandOrigin = "config"
command = "echo 'Deploying TK999 Betting Platform'"
functions = "/Users/test/startups/deploy-68cc53904a126d00086a9168/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[template]

[template.environment]
NODE_VERSION = "18"

[dev]
framework = "#static"

[functions]

[functions."*"]

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]