# Netlify configuration for static file deployment
[build]
  # Since we're deploying built files directly, we don't need to build
  command = "echo 'Using pre-built files'"
  publish = "deployment/"
  
# Temporarily remove all redirects for testing
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200