[build]
  command = "npm run build"
  publish = "dist"
  base = "/"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3000/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200